<?xml version="1.0"?>
<!--
    - Base      : koala2-silver
    - Sensor    : IR + camera
-->    
<robot name="koala" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find koala_description)/urdf/koala_library.urdf.xacro" />

  <koala2_silver/>
  <picoitx x_loc="-${base_length/3}" y_loc="0" z_loc="${base_height+wheel_radius}"/>
  <camera x_loc="${base_length/3}" y_loc="0" z_loc="${base_height+wheel_radius}"/>
  <!-- <sensor_ir              parent="base_link"/> -->
  <!-- <sensor_camera          parent="base_link"/> -->
</robot>
