<?xml version="1.0"?>
<!-- http://www.k-team.com/mobile-robotics-products/old-products/koala/picoitx -->
<robot name="picoitx" xmlns:xacro="http://www.ros.org/wiki/xacro">


  <xacro:property name="picoitx_length" value="0.125" />
  <xacro:property name="picoitx_width" value="0.145" />
  <xacro:property name="picoitx_height" value="0.091" />

  <xacro:macro name="picoitx" params="x_loc y_loc z_loc"> 

    <joint name="picoitx_joint" type="fixed">
      <origin xyz="${x_loc} ${y_loc} ${z_loc}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="picoitx_link"/>
    </joint>

    <link name="picoitx_link">
      <visual>
	<origin xyz="0 0 ${picoitx_height/2}" rpy="0 0 0" />
	<geometry>
          <box size="${picoitx_length} ${picoitx_width} ${picoitx_height}"/>
	</geometry>
	<material name="gray">
	  <color rgba="0.5 0.5 0.5 1"/>
	</material>
      </visual>
      <collision>
        <origin xyz="0 0 ${picoitx_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${picoitx_length} ${picoitx_width} ${picoitx_height}"/>
        </geometry>
      </collision>
      <!-- <inertial> -->
      <!--   <mass value="0.860"/> -->
      <!-- </inertial> -->
    </link>

  </xacro:macro>
</robot>
