<?xml version="1.0"?>
<robot name="koala" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="base_width" value=".26" />
  <xacro:property name="base_length" value=".3" />
  <xacro:property name="base_height" value=".1" />
  <xacro:property name="wheel_radius" value=".045" />
  <xacro:property name="wheel_length" value=".08" />
  <xacro:property name="M_PI" value="3.1415926535897931" /> 

  <xacro:macro name="wheel" params="name *position">

    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="position"/>
      <parent link="base_link"/>
      <child link="${name}_link"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <geometry>
	  <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
	<origin xyz="0 0 0" rpy="0 0 0" />
        <material name="wheel">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
	  <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>
    <joint name="base_to_${name}" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="koala2_silver"> 
    <link name="base_link">
      <visual>
	<origin xyz="0 0  ${base_height/2+wheel_radius}" rpy="0 0 0" />
	<geometry>
	  <mesh filename="package://koala_description/meshes/base.stl"/>
          <!--<box size="${base_length} ${base_width} ${base_height}"/>-->
	</geometry>
	<material name="gray">
	  <color rgba="0.5 0.5 0.5 1"/>
	</material>
      </visual>
    </link>

    <xacro:wheel name="wheel1">
      <origin rpy="${M_PI/2} 0 0" xyz="0.12 ${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>

    <xacro:wheel name="wheel2">
      <origin rpy="${M_PI/2} 0 0" xyz="0. ${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>

    <xacro:wheel name="wheel3">
      <origin rpy="${M_PI/2} 0 0" xyz="-0.12 ${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>


    <xacro:wheel name="wheel4">
      <origin rpy="${M_PI/2} 0 0" xyz="0.12 -${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>

    <xacro:wheel name="wheel5">
      <origin rpy="${M_PI/2} 0 0" xyz="0 -${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>

    <xacro:wheel name="wheel6">
      <origin rpy="${M_PI/2} 0 0" xyz="-0.12 -${wheel_length/2 + base_width/2} ${wheel_radius}"/>
    </xacro:wheel>

    <!-- <link name="camera_base_link"> -->
    <!--   <visual> -->
    <!--     <origin xyz="${base_length/4} 0  ${base_height+wheel_radius}" rpy="0 0 0" /> -->
    <!--     <geometry> -->
    <!--       <cylinder length="0.1" radius="0.05"/> -->
    <!--     </geometry> -->
    <!--     <material name="gray"> -->
    <!-- 	<color rgba="0.5 0.5 0.5 1"/> -->
    <!--     </material> -->
    <!--   </visual> -->
    <!--    <collision> -->
    <!--       <geometry> -->
    <!-- 	  <cylinder length="0.1" radius="0.05"/> -->
    <!--       </geometry> -->
    <!--     </collision> -->
    <!--   </link> -->
    <!--   <joint name="base_to_camera_base" type="fixed"> -->
    <!--     <parent link="base_link"/> -->
    <!--     <child link="camera_base_link"/> -->
    <!--   </joint> -->

  </xacro:macro>
</robot>
